name: Update Comment
on:
  issue_comment:
    types: [created]
jobs:
  update-comment:
    if: contains(github.event.comment.body, 'Hello')
    ## Restrict trigger, only when a comment is added on a pull request
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: PUSH COMMENT
        uses: ./.github/actions/pr_comment_webhook
